version: '3.1'

services:
    db:
        image: postgres:12.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: password
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080